import '../styles/global.css';

import { Metadata } from 'next';
import ClientProvider from '../components/ClientProvider';

export const metadata: Metadata = {
  title: 'Star Wars',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" type="image/png" />
      </head>
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
